version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: dungeon-ai-mongo-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: dungeon-ai
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - dungeon-ai-dev-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: dungeon-ai-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - dungeon-ai-dev-network

  # Backend API (Development)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: dungeon-ai-backend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/dungeon-ai
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET:-dungeon_ai_super_secret_jwt_key_2024_secure_random_string}
      - PORT=3001
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:19006
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    networks:
      - dungeon-ai-dev-network
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_dev_logs:/app/logs

networks:
  dungeon-ai-dev-network:
    driver: bridge

volumes:
  mongodb_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  backend_dev_logs:
    driver: local